# coding: utf-8

"""
    Visier User Management APIs

    Visier APIs for managing users within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from visier_user_management_python_sdk.pydantic.profile_assigned_for_local_tenant_dto import ProfileAssignedForLocalTenantDTO

class AllProfileAssignedForLocalTenantDTO(BaseModel):
    # A list of objects representing the user profiles assigned to the user and their validity range.
    assigned_profiles: typing.Optional[typing.List[ProfileAssignedForLocalTenantDTO]] = Field(None, alias='assignedProfiles')
    class Config:
        arbitrary_types_allowed = True
