# coding: utf-8

"""
    Visier User Management APIs

    Visier APIs for managing users within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from visier_user_management_python_sdk.pydantic.permission_assigned_for_local_tenant_dto import PermissionAssignedForLocalTenantDTO

class AllPermissionsAssignedForLocalTenantDTO(BaseModel):
    # A list of objects representing the user's permissions.
    assigned_permissions: typing.Optional[typing.List[PermissionAssignedForLocalTenantDTO]] = Field(None, alias='assignedPermissions')
    class Config:
        arbitrary_types_allowed = True
