# coding: utf-8

"""
    Visier User Management APIs

    Visier APIs for managing users within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from visier_user_management_python_sdk.pydantic.permission import Permission

class AssignRevokePermissionsRequest(BaseModel):
    # A list of objects representing the permissions to assign to or remove from users.
    permissions: typing.Optional[typing.List[Permission]] = Field(None, alias='permissions')
    class Config:
        arbitrary_types_allowed = True
