# coding: utf-8

"""
    Visier User Management APIs

    Visier APIs for managing users within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class AssignRevokePermissionByUserDTO(BaseModel):
    # The unique identifier associated with the user.
    user_id: typing.Optional[str] = Field(None, alias='userId')

    # The user's username. This is typically the user's email, such as john@visier.com.
    username: typing.Optional[str] = Field(None, alias='username')

    # A meaningful message about the user permission.
    message: typing.Optional[str] = Field(None, alias='message')
    class Config:
        arbitrary_types_allowed = True
