# coding: utf-8

"""
    Visier User Management APIs

    Visier APIs for managing users within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class PermissionAssignedForLocalTenantDTO(BaseModel):
    # A user-defined description of the permission.
    description: typing.Optional[str] = Field(None, alias='description')

    # The unique identifier associated with the permission.
    permission_id: typing.Optional[str] = Field(None, alias='permissionId')

    # An identifiable permission name to display in Visier, such as \"Diversity Access\".
    display_name: typing.Optional[str] = Field(None, alias='displayName')
    class Config:
        arbitrary_types_allowed = True
