# coding: utf-8

"""
    Visier User Management APIs

    Visier APIs for managing users within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from visier_user_management_python_sdk.pydantic.user_security_assignments_dto import UserSecurityAssignmentsDTO

class TenantAssignmentsDTO(BaseModel):
    # The unique identifier associated with the tenant.
    tenant_code: typing.Optional[str] = Field(None, alias='tenantCode')

    # The state of the user group assignment. Valid values are Succeed or Failed.
    status: typing.Optional[Literal["Unknown", "Succeed", "Failed"]] = Field(None, alias='status')

    # A detailed description of the request outcome, if available.
    message: typing.Optional[str] = Field(None, alias='message')

    # A list of objects representing the user group and user assignments.
    assignments: typing.Optional[typing.List[UserSecurityAssignmentsDTO]] = Field(None, alias='assignments')
    class Config:
        arbitrary_types_allowed = True
