# coding: utf-8

"""
    Visier User Management APIs

    Visier APIs for managing users within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from visier_user_management_python_sdk.pydantic.users_api_failure_dto import UsersAPIFailureDTO
from visier_user_management_python_sdk.pydantic.users_api_success_dto import UsersAPISuccessDTO

class UsersAPIResponseDTO(BaseModel):
    # The users for which the request succeeded.
    successes: typing.Optional[typing.List[UsersAPISuccessDTO]] = Field(None, alias='successes')

    # The users for which the request failed.
    failures: typing.Optional[typing.List[UsersAPIFailureDTO]] = Field(None, alias='failures')
    class Config:
        arbitrary_types_allowed = True
