# coding: utf-8

"""
    Visier User Management APIs

    Visier APIs for managing users within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from visier_user_management_python_sdk.pydantic.user_group_get_api_response_dto import UserGroupGetAPIResponseDTO

class UserGroupsGetAPIResponseDTO(BaseModel):
    # A list of user groups.
    user_groups: typing.Optional[typing.List[UserGroupGetAPIResponseDTO]] = Field(None, alias='userGroups')

    # The number of results to return. The maximum number of users to retrieve is 1000.
    limit: typing.Optional[int] = Field(None, alias='limit')

    # The index to start retrieving results from, also known as offset.
    start: typing.Optional[int] = Field(None, alias='start')
    class Config:
        arbitrary_types_allowed = True
