# coding: utf-8

"""
    Visier User Management APIs

    Visier APIs for managing users within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class UserCreationAPIRequestDTO(BaseModel):
    # The user's username. This is typically the user's email, such as john@visier.com.
    username: typing.Optional[str] = Field(None, alias='username')

    # An identifiable name to display within Visier. For example, \"John Smith\".
    display_name: typing.Optional[str] = Field(None, alias='displayName')

    # If applicable, and if available, the user employee ID in the data.
    employee_id: typing.Optional[str] = Field(None, alias='employeeId')

    # If false, the user account is disabled.
    account_enabled: typing.Optional[str] = Field(None, alias='accountEnabled')

    # The user's email. This is used if the user's email is different from their username. For example, \"john.doe@visier.com\".
    email: typing.Optional[str] = Field(None, alias='email')
    class Config:
        arbitrary_types_allowed = True
