# coding: utf-8

"""
    Visier User Management APIs

    Visier APIs for managing users within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

import unittest

import visier_user_management_python_sdk
from visier_user_management_python_sdk.model.user_management_get_application_logs_xlsx_response import UserManagementGetApplicationLogsXlsxResponse
from visier_user_management_python_sdk import configuration


class TestUserManagementGetApplicationLogsXlsxResponse(unittest.TestCase):
    """UserManagementGetApplicationLogsXlsxResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
