# coding: utf-8

"""
    Visier User Management APIs

    Visier APIs for managing users within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

import unittest

import visier_user_management_python_sdk
from visier_user_management_python_sdk.model.permission_response_dto import PermissionResponseDTO
from visier_user_management_python_sdk import configuration


class TestPermissionResponseDTO(unittest.TestCase):
    """PermissionResponseDTO unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
