# coding: utf-8

"""
    Visier User Management APIs

    Visier APIs for managing users within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

import unittest

import visier_user_management_python_sdk
from visier_user_management_python_sdk.model.user_groups_users_for_tenant_dto import UserGroupsUsersForTenantDTO
from visier_user_management_python_sdk import configuration


class TestUserGroupsUsersForTenantDTO(unittest.TestCase):
    """UserGroupsUsersForTenantDTO unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
