# coding: utf-8

"""
    Visier User Management APIs

    Visier APIs for managing users within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

import unittest

import visier_user_management_python_sdk
from visier_user_management_python_sdk.model.assign_revoke_permission_by_user_dto import AssignRevokePermissionByUserDTO
from visier_user_management_python_sdk import configuration


class TestAssignRevokePermissionByUserDTO(unittest.TestCase):
    """AssignRevokePermissionByUserDTO unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
