# coding: utf-8

"""
    Visier User Management APIs

    Visier APIs for managing users within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from visier_user_management_python_sdk import schemas  # noqa: F401


class AdditionalCapabilitiesDTO(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def additionalCapabilities() -> typing.Type['AdditionalCapabilitiesDTOAdditionalCapabilities']:
                return AdditionalCapabilitiesDTOAdditionalCapabilities
            __annotations__ = {
                "additionalCapabilities": additionalCapabilities,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["additionalCapabilities"]) -> 'AdditionalCapabilitiesDTOAdditionalCapabilities': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["additionalCapabilities", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["additionalCapabilities"]) -> typing.Union['AdditionalCapabilitiesDTOAdditionalCapabilities', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["additionalCapabilities", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        additionalCapabilities: typing.Union['AdditionalCapabilitiesDTOAdditionalCapabilities', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'AdditionalCapabilitiesDTO':
        return super().__new__(
            cls,
            *args,
            additionalCapabilities=additionalCapabilities,
            _configuration=_configuration,
            **kwargs,
        )

from visier_user_management_python_sdk.model.additional_capabilities_dto_additional_capabilities import AdditionalCapabilitiesDTOAdditionalCapabilities
