# coding: utf-8

"""
    Visier User Management APIs

    Visier APIs for managing users within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from visier_user_management_python_sdk import schemas  # noqa: F401


class AllUserGroupsAssignedForLocalTenantDTO(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            
            
            class assignedUserGroups(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['UserGroupAssignedForLocalTenantDTO']:
                        return UserGroupAssignedForLocalTenantDTO
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['UserGroupAssignedForLocalTenantDTO'], typing.List['UserGroupAssignedForLocalTenantDTO']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'assignedUserGroups':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'UserGroupAssignedForLocalTenantDTO':
                    return super().__getitem__(i)
            __annotations__ = {
                "assignedUserGroups": assignedUserGroups,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["assignedUserGroups"]) -> MetaOapg.properties.assignedUserGroups: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["assignedUserGroups", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["assignedUserGroups"]) -> typing.Union[MetaOapg.properties.assignedUserGroups, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["assignedUserGroups", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        assignedUserGroups: typing.Union[MetaOapg.properties.assignedUserGroups, list, tuple, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'AllUserGroupsAssignedForLocalTenantDTO':
        return super().__new__(
            cls,
            *args,
            assignedUserGroups=assignedUserGroups,
            _configuration=_configuration,
            **kwargs,
        )

from visier_user_management_python_sdk.model.user_group_assigned_for_local_tenant_dto import UserGroupAssignedForLocalTenantDTO
