# coding: utf-8

"""
    Visier User Management APIs

    Visier APIs for managing users within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from visier_user_management_python_sdk import schemas  # noqa: F401


class AssignRevokePermissionByPermissionDTO(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    The results of the permission assignment or removal.
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def permission() -> typing.Type['PermissionAssignedForLocalTenantDTO']:
                return PermissionAssignedForLocalTenantDTO
            
            
            class users(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['AssignRevokePermissionByUserDTO']:
                        return AssignRevokePermissionByUserDTO
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['AssignRevokePermissionByUserDTO'], typing.List['AssignRevokePermissionByUserDTO']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'users':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'AssignRevokePermissionByUserDTO':
                    return super().__getitem__(i)
            __annotations__ = {
                "permission": permission,
                "users": users,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["permission"]) -> 'PermissionAssignedForLocalTenantDTO': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["users"]) -> MetaOapg.properties.users: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["permission", "users", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["permission"]) -> typing.Union['PermissionAssignedForLocalTenantDTO', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["users"]) -> typing.Union[MetaOapg.properties.users, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["permission", "users", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        permission: typing.Union['PermissionAssignedForLocalTenantDTO', schemas.Unset] = schemas.unset,
        users: typing.Union[MetaOapg.properties.users, list, tuple, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'AssignRevokePermissionByPermissionDTO':
        return super().__new__(
            cls,
            *args,
            permission=permission,
            users=users,
            _configuration=_configuration,
            **kwargs,
        )

from visier_user_management_python_sdk.model.assign_revoke_permission_by_user_dto import AssignRevokePermissionByUserDTO
from visier_user_management_python_sdk.model.permission_assigned_for_local_tenant_dto import PermissionAssignedForLocalTenantDTO
