# coding: utf-8

"""
    Visier User Management APIs

    Visier APIs for managing users within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from visier_user_management_python_sdk import schemas  # noqa: F401


class CapabilitiesDTO(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            capability = schemas.StrSchema
            accessLevel = schemas.StrSchema
            viewLevel = schemas.StrSchema
            __annotations__ = {
                "capability": capability,
                "accessLevel": accessLevel,
                "viewLevel": viewLevel,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["capability"]) -> MetaOapg.properties.capability: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["accessLevel"]) -> MetaOapg.properties.accessLevel: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["viewLevel"]) -> MetaOapg.properties.viewLevel: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["capability", "accessLevel", "viewLevel", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["capability"]) -> typing.Union[MetaOapg.properties.capability, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["accessLevel"]) -> typing.Union[MetaOapg.properties.accessLevel, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["viewLevel"]) -> typing.Union[MetaOapg.properties.viewLevel, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["capability", "accessLevel", "viewLevel", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        capability: typing.Union[MetaOapg.properties.capability, str, schemas.Unset] = schemas.unset,
        accessLevel: typing.Union[MetaOapg.properties.accessLevel, str, schemas.Unset] = schemas.unset,
        viewLevel: typing.Union[MetaOapg.properties.viewLevel, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'CapabilitiesDTO':
        return super().__new__(
            cls,
            *args,
            capability=capability,
            accessLevel=accessLevel,
            viewLevel=viewLevel,
            _configuration=_configuration,
            **kwargs,
        )
