# coding: utf-8

"""
    Visier User Management APIs

    Visier APIs for managing users within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from visier_user_management_python_sdk import schemas  # noqa: F401


class UsersToUserGroupRequestDTO(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            userGroupId = schemas.StrSchema
        
            @staticmethod
            def userIds() -> typing.Type['UsersToUserGroupRequestDTOUserIds']:
                return UsersToUserGroupRequestDTOUserIds
            __annotations__ = {
                "userGroupId": userGroupId,
                "userIds": userIds,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["userGroupId"]) -> MetaOapg.properties.userGroupId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["userIds"]) -> 'UsersToUserGroupRequestDTOUserIds': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["userGroupId", "userIds", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["userGroupId"]) -> typing.Union[MetaOapg.properties.userGroupId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["userIds"]) -> typing.Union['UsersToUserGroupRequestDTOUserIds', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["userGroupId", "userIds", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        userGroupId: typing.Union[MetaOapg.properties.userGroupId, str, schemas.Unset] = schemas.unset,
        userIds: typing.Union['UsersToUserGroupRequestDTOUserIds', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'UsersToUserGroupRequestDTO':
        return super().__new__(
            cls,
            *args,
            userGroupId=userGroupId,
            userIds=userIds,
            _configuration=_configuration,
            **kwargs,
        )

from visier_user_management_python_sdk.model.users_to_user_group_request_dto_user_ids import UsersToUserGroupRequestDTOUserIds
