# coding: utf-8

"""
    Visier User Management APIs

    Visier APIs for managing users within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from visier_user_management_python_sdk import schemas  # noqa: F401


class UsersAPIResponseDTO(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            
            
            class successes(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['UsersAPISuccessDTO']:
                        return UsersAPISuccessDTO
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['UsersAPISuccessDTO'], typing.List['UsersAPISuccessDTO']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'successes':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'UsersAPISuccessDTO':
                    return super().__getitem__(i)
            
            
            class failures(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['UsersAPIFailureDTO']:
                        return UsersAPIFailureDTO
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['UsersAPIFailureDTO'], typing.List['UsersAPIFailureDTO']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'failures':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'UsersAPIFailureDTO':
                    return super().__getitem__(i)
            __annotations__ = {
                "successes": successes,
                "failures": failures,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["successes"]) -> MetaOapg.properties.successes: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["failures"]) -> MetaOapg.properties.failures: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["successes", "failures", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["successes"]) -> typing.Union[MetaOapg.properties.successes, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["failures"]) -> typing.Union[MetaOapg.properties.failures, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["successes", "failures", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        successes: typing.Union[MetaOapg.properties.successes, list, tuple, schemas.Unset] = schemas.unset,
        failures: typing.Union[MetaOapg.properties.failures, list, tuple, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'UsersAPIResponseDTO':
        return super().__new__(
            cls,
            *args,
            successes=successes,
            failures=failures,
            _configuration=_configuration,
            **kwargs,
        )

from visier_user_management_python_sdk.model.users_api_failure_dto import UsersAPIFailureDTO
from visier_user_management_python_sdk.model.users_api_success_dto import UsersAPISuccessDTO
