# coding: utf-8
"""
    Visier User Management APIs

    Visier APIs for managing users within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

import typing
import inspect
from datetime import date, datetime
from visier_user_management_python_sdk.client_custom import ClientCustom
from visier_user_management_python_sdk.configuration import Configuration
from visier_user_management_python_sdk.api_client import ApiClient
from visier_user_management_python_sdk.type_util import copy_signature
from visier_user_management_python_sdk.apis.tags.user_management_api import UserManagementApi
from visier_user_management_python_sdk.apis.tags.user_management_v2_api import UserManagementV2Api



class VisierUserManagement(ClientCustom):

    def __init__(self, configuration: typing.Union[Configuration, None] = None, **kwargs):
        super().__init__(configuration, **kwargs)
        if (len(kwargs) > 0):
            configuration = Configuration(**kwargs)
        if (configuration is None):
            raise Exception("configuration is required")
        api_client = ApiClient(configuration)
        self.user_management: UserManagementApi = UserManagementApi(api_client)
        self.user_management_v2: UserManagementV2Api = UserManagementV2Api(api_client)
