# coding: utf-8

"""
    Visier User Management APIs

    Visier APIs for managing users within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from visier_user_management_python_sdk.paths.v1_admin_users.post import AddUserRaw
from visier_user_management_python_sdk.paths.v1_admin_user_groups_users.put import AddUsersToUserGroupRaw
from visier_user_management_python_sdk.paths.v1_admin_permissions_users.put import AssignPermissionsRaw
from visier_user_management_python_sdk.paths.v1_admin_user_groups_permissions.put import AssignPermissionsToUserGroupsRaw
from visier_user_management_python_sdk.paths.v1_admin_users_user_id.delete import DeleteUserRaw
from visier_user_management_python_sdk.paths.v1_admin_users_reports_permissions_list.get import GetAllPermissionsXlsxRaw
from visier_user_management_python_sdk.paths.v1_admin_user_groups.get import GetAllUserGroupsRaw
from visier_user_management_python_sdk.paths.v1_admin_users.get import GetAllUsersRaw
from visier_user_management_python_sdk.paths.v1_admin_users_reports_application_logs.get import GetApplicationLogsXlsxRaw
from visier_user_management_python_sdk.paths.v1_admin_users_user_id_reports_data_security.get import GetDataSecurityReportXlsxRaw
from visier_user_management_python_sdk.paths.v1_admin_permissions_permission_id_users.get import GetPermissionAssignedUsersRaw
from visier_user_management_python_sdk.paths.v1_admin_users_reports_profile_assignments.get import GetProfileAssignmentsXlsxRaw
from visier_user_management_python_sdk.paths.v1_admin_users_user_id.get import GetUserDetailRaw
from visier_user_management_python_sdk.paths.v1_admin_user_groups_user_group_id_users.get import GetUserGroupUsersRaw
from visier_user_management_python_sdk.paths.v1_admin_users_reports_permission_assignments.get import GetUserPermissionsXlsxRaw
from visier_user_management_python_sdk.paths.v1_admin_permissions_users.delete import RemovePermissionsRaw
from visier_user_management_python_sdk.paths.v1_admin_user_groups_users.delete import RemoveUsersFromUserGroupRaw
from visier_user_management_python_sdk.paths.v1_admin_user_groups_permissions.delete import RevokePermissionsFromUserGroupsRaw
from visier_user_management_python_sdk.paths.v1_admin_users_user_id.put import UpdateUserRaw


class UserManagementApiRaw(
    AddUserRaw,
    AddUsersToUserGroupRaw,
    AssignPermissionsRaw,
    AssignPermissionsToUserGroupsRaw,
    DeleteUserRaw,
    GetAllPermissionsXlsxRaw,
    GetAllUserGroupsRaw,
    GetAllUsersRaw,
    GetApplicationLogsXlsxRaw,
    GetDataSecurityReportXlsxRaw,
    GetPermissionAssignedUsersRaw,
    GetProfileAssignmentsXlsxRaw,
    GetUserDetailRaw,
    GetUserGroupUsersRaw,
    GetUserPermissionsXlsxRaw,
    RemovePermissionsRaw,
    RemoveUsersFromUserGroupRaw,
    RevokePermissionsFromUserGroupsRaw,
    UpdateUserRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
