# coding: utf-8

"""
    Visier User Management APIs

    Visier APIs for managing users within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from visier_user_management_python_sdk.paths.v2_admin_users.post import AddUsersRaw
from visier_user_management_python_sdk.paths.v2_admin_users.delete import DeleteUsersRaw
from visier_user_management_python_sdk.paths.v2_admin_users.put import UpdateUsersRaw


class UserManagementV2ApiRaw(
    AddUsersRaw,
    DeleteUsersRaw,
    UpdateUsersRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
