# coding: utf-8

"""
    Visier User Management APIs

    Visier APIs for managing users within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from visier_user_management_python_sdk.paths.v2_admin_users.post import AddUsers
from visier_user_management_python_sdk.paths.v2_admin_users.delete import DeleteUsers
from visier_user_management_python_sdk.paths.v2_admin_users.put import UpdateUsers
from visier_user_management_python_sdk.apis.tags.user_management_v2_api_raw import UserManagementV2ApiRaw


class UserManagementV2Api(
    AddUsers,
    DeleteUsers,
    UpdateUsers,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: UserManagementV2ApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = UserManagementV2ApiRaw(api_client)
