# coding: utf-8

"""
    Visier User Management APIs

    Visier APIs for managing users within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from visier_user_management_python_sdk.paths.v1_admin_users.post import AddUser
from visier_user_management_python_sdk.paths.v1_admin_user_groups_users.put import AddUsersToUserGroup
from visier_user_management_python_sdk.paths.v1_admin_permissions_users.put import AssignPermissions
from visier_user_management_python_sdk.paths.v1_admin_user_groups_permissions.put import AssignPermissionsToUserGroups
from visier_user_management_python_sdk.paths.v1_admin_users_user_id.delete import DeleteUser
from visier_user_management_python_sdk.paths.v1_admin_users_reports_permissions_list.get import GetAllPermissionsXlsx
from visier_user_management_python_sdk.paths.v1_admin_user_groups.get import GetAllUserGroups
from visier_user_management_python_sdk.paths.v1_admin_users.get import GetAllUsers
from visier_user_management_python_sdk.paths.v1_admin_users_reports_application_logs.get import GetApplicationLogsXlsx
from visier_user_management_python_sdk.paths.v1_admin_users_user_id_reports_data_security.get import GetDataSecurityReportXlsx
from visier_user_management_python_sdk.paths.v1_admin_permissions_permission_id_users.get import GetPermissionAssignedUsers
from visier_user_management_python_sdk.paths.v1_admin_users_reports_profile_assignments.get import GetProfileAssignmentsXlsx
from visier_user_management_python_sdk.paths.v1_admin_users_user_id.get import GetUserDetail
from visier_user_management_python_sdk.paths.v1_admin_user_groups_user_group_id_users.get import GetUserGroupUsers
from visier_user_management_python_sdk.paths.v1_admin_users_reports_permission_assignments.get import GetUserPermissionsXlsx
from visier_user_management_python_sdk.paths.v1_admin_permissions_users.delete import RemovePermissions
from visier_user_management_python_sdk.paths.v1_admin_user_groups_users.delete import RemoveUsersFromUserGroup
from visier_user_management_python_sdk.paths.v1_admin_user_groups_permissions.delete import RevokePermissionsFromUserGroups
from visier_user_management_python_sdk.paths.v1_admin_users_user_id.put import UpdateUser
from visier_user_management_python_sdk.apis.tags.user_management_api_raw import UserManagementApiRaw


class UserManagementApi(
    AddUser,
    AddUsersToUserGroup,
    AssignPermissions,
    AssignPermissionsToUserGroups,
    DeleteUser,
    GetAllPermissionsXlsx,
    GetAllUserGroups,
    GetAllUsers,
    GetApplicationLogsXlsx,
    GetDataSecurityReportXlsx,
    GetPermissionAssignedUsers,
    GetProfileAssignmentsXlsx,
    GetUserDetail,
    GetUserGroupUsers,
    GetUserPermissionsXlsx,
    RemovePermissions,
    RemoveUsersFromUserGroup,
    RevokePermissionsFromUserGroups,
    UpdateUser,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: UserManagementApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = UserManagementApiRaw(api_client)
