# coding: utf-8

"""
    Visier User Management APIs

    Visier APIs for managing users within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_user_management_python_sdk.type.additional_capabilities_dto_additional_capabilities import AdditionalCapabilitiesDTOAdditionalCapabilities

class RequiredAdditionalCapabilitiesDTO(TypedDict):
    pass

class OptionalAdditionalCapabilitiesDTO(TypedDict, total=False):
    additionalCapabilities: AdditionalCapabilitiesDTOAdditionalCapabilities

class AdditionalCapabilitiesDTO(RequiredAdditionalCapabilitiesDTO, OptionalAdditionalCapabilitiesDTO):
    pass
