# coding: utf-8

"""
    Visier User Management APIs

    Visier APIs for managing users within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_user_management_python_sdk.type.user_group_assigned_for_local_tenant_dto import UserGroupAssignedForLocalTenantDTO

class RequiredAllUserGroupsAssignedForLocalTenantDTO(TypedDict):
    pass

class OptionalAllUserGroupsAssignedForLocalTenantDTO(TypedDict, total=False):
    # A list of objects representing the available user groups.
    assignedUserGroups: typing.List[UserGroupAssignedForLocalTenantDTO]

class AllUserGroupsAssignedForLocalTenantDTO(RequiredAllUserGroupsAssignedForLocalTenantDTO, OptionalAllUserGroupsAssignedForLocalTenantDTO):
    pass
