# coding: utf-8

"""
    Visier User Management APIs

    Visier APIs for managing users within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_user_management_python_sdk.type.permission_assigned_for_local_tenant_dto import PermissionAssignedForLocalTenantDTO

class RequiredAllPermissionsAssignedForLocalTenantDTO(TypedDict):
    pass

class OptionalAllPermissionsAssignedForLocalTenantDTO(TypedDict, total=False):
    # A list of objects representing the user's permissions.
    assignedPermissions: typing.List[PermissionAssignedForLocalTenantDTO]

class AllPermissionsAssignedForLocalTenantDTO(RequiredAllPermissionsAssignedForLocalTenantDTO, OptionalAllPermissionsAssignedForLocalTenantDTO):
    pass
