# coding: utf-8

"""
    Visier User Management APIs

    Visier APIs for managing users within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_user_management_python_sdk.type.profile_assigned_for_local_tenant_dto import ProfileAssignedForLocalTenantDTO

class RequiredAllProfileAssignedForLocalTenantDTO(TypedDict):
    pass

class OptionalAllProfileAssignedForLocalTenantDTO(TypedDict, total=False):
    # A list of objects representing the user profiles assigned to the user and their validity range.
    assignedProfiles: typing.List[ProfileAssignedForLocalTenantDTO]

class AllProfileAssignedForLocalTenantDTO(RequiredAllProfileAssignedForLocalTenantDTO, OptionalAllProfileAssignedForLocalTenantDTO):
    pass
