# coding: utf-8

"""
    Visier User Management APIs

    Visier APIs for managing users within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredCapabilitiesDTO(TypedDict):
    pass

class OptionalCapabilitiesDTO(TypedDict, total=False):
    # The name of the capability.
    capability: str

    # The access level of the profile for the given capability.
    accessLevel: str

    # The view level of the profile for the given capability.
    viewLevel: str

class CapabilitiesDTO(RequiredCapabilitiesDTO, OptionalCapabilitiesDTO):
    pass
