# coding: utf-8

"""
    Visier User Management APIs

    Visier APIs for managing users within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_user_management_python_sdk.type.permission_assigned_by_tenant_dto import PermissionAssignedByTenantDTO

class RequiredPermissionAssignedUsersDTO(TypedDict):
    pass

class OptionalPermissionAssignedUsersDTO(TypedDict, total=False):
    # A list of objects representing the users that are assigned the specific permission, organized by the tenants the users belong to.
    tenants: typing.List[PermissionAssignedByTenantDTO]

    # The number of results to return. The maximum number of tenants to retrieve is 100.
    limit: int

    # The index to start retrieving results from, also known as offset. The index begins at 0.
    start: int

class PermissionAssignedUsersDTO(RequiredPermissionAssignedUsersDTO, OptionalPermissionAssignedUsersDTO):
    pass
