# coding: utf-8

"""
    Visier User Management APIs

    Visier APIs for managing users within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_user_management_python_sdk.type.user_group_get_api_response_dto import UserGroupGetAPIResponseDTO

class RequiredPermissionsToUserGroupForTenantDTO(TypedDict):
    pass

class OptionalPermissionsToUserGroupForTenantDTO(TypedDict, total=False):
    # The unique identifier associated with the tenant.
    tenantCode: str

    # The state of the permission assignment or removal. Valid values are Succeed or Failed.
    status: str

    # A detailed description of the request outcome, if available.
    message: str

    # A list of objects representing user groups and the permissions to assign to or remove from them.
    userGroups: typing.List[UserGroupGetAPIResponseDTO]

class PermissionsToUserGroupForTenantDTO(RequiredPermissionsToUserGroupForTenantDTO, OptionalPermissionsToUserGroupForTenantDTO):
    pass
