# coding: utf-8

"""
    Visier User Management APIs

    Visier APIs for managing users within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_user_management_python_sdk.type.permission_user_ids import PermissionUserIds

class RequiredPermission(TypedDict):
    pass

class OptionalPermission(TypedDict, total=False):
    # The unique identifier associated with a permission.
    permissionId: str

    userIds: PermissionUserIds

class Permission(RequiredPermission, OptionalPermission):
    pass
