# coding: utf-8

"""
    Visier User Management APIs

    Visier APIs for managing users within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredPermissionAssignedForLocalTenantDTO(TypedDict):
    pass

class OptionalPermissionAssignedForLocalTenantDTO(TypedDict, total=False):
    # A user-defined description of the permission.
    description: str

    # The unique identifier associated with the permission.
    permissionId: str

    # An identifiable permission name to display in Visier, such as \"Diversity Access\".
    displayName: str

class PermissionAssignedForLocalTenantDTO(RequiredPermissionAssignedForLocalTenantDTO, OptionalPermissionAssignedForLocalTenantDTO):
    pass
