# coding: utf-8

"""
    Visier User Management APIs

    Visier APIs for managing users within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_user_management_python_sdk.type.additional_capabilities_dto import AdditionalCapabilitiesDTO
from visier_user_management_python_sdk.type.capabilities_dto import CapabilitiesDTO

class RequiredProfileAssignedForLocalTenantDTO(TypedDict):
    pass

class OptionalProfileAssignedForLocalTenantDTO(TypedDict, total=False):
    # The unique identifier associated with the profile.
    profileId: str

    # An identifiable profile name to display in Visier, such as \"Partner Service Manager\".
    displayName: str

    # An inclusive date-time when this profile is active.
    validityStartTime: str

    # An exclusive date-time when this profile is no longer active.
    validityEndTime: str

    # A list of objects representing the access that this profile has for the capabilities of this profile.
    capabilities: typing.List[CapabilitiesDTO]

    # A list of the additional capabilities that are assigned to this profile.
    additionalCapabilities: AdditionalCapabilitiesDTO

class ProfileAssignedForLocalTenantDTO(RequiredProfileAssignedForLocalTenantDTO, OptionalProfileAssignedForLocalTenantDTO):
    pass
