# coding: utf-8

"""
    Visier User Management APIs

    Visier APIs for managing users within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_user_management_python_sdk.type.user_security_assignments_dto import UserSecurityAssignmentsDTO

class RequiredTenantAssignmentsDTO(TypedDict):
    pass

class OptionalTenantAssignmentsDTO(TypedDict, total=False):
    # The unique identifier associated with the tenant.
    tenantCode: str

    # The state of the user group assignment. Valid values are Succeed or Failed.
    status: str

    # A detailed description of the request outcome, if available.
    message: str

    # A list of objects representing the user group and user assignments.
    assignments: typing.List[UserSecurityAssignmentsDTO]

class TenantAssignmentsDTO(RequiredTenantAssignmentsDTO, OptionalTenantAssignmentsDTO):
    pass
