# coding: utf-8

"""
    Visier User Management APIs

    Visier APIs for managing users within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_user_management_python_sdk.type.users_api_failure_dto import UsersAPIFailureDTO
from visier_user_management_python_sdk.type.users_api_success_dto import UsersAPISuccessDTO

class RequiredUsersAPIResponseDTO(TypedDict):
    pass

class OptionalUsersAPIResponseDTO(TypedDict, total=False):
    # The users for which the request succeeded.
    successes: typing.List[UsersAPISuccessDTO]

    # The users for which the request failed.
    failures: typing.List[UsersAPIFailureDTO]

class UsersAPIResponseDTO(RequiredUsersAPIResponseDTO, OptionalUsersAPIResponseDTO):
    pass
