# coding: utf-8

"""
    Visier User Management APIs

    Visier APIs for managing users within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_user_management_python_sdk.type.simple_user_dto import SimpleUserDTO

class RequiredUserSecurityAssignmentsDTO(TypedDict):
    pass

class OptionalUserSecurityAssignmentsDTO(TypedDict, total=False):
    # The unique identifier associated with the user group.
    id: str

    # The name of the user group.
    name: str

    # A list of objects representing the users assigned to or removed from the user group.
    users: typing.List[SimpleUserDTO]

class UserSecurityAssignmentsDTO(RequiredUserSecurityAssignmentsDTO, OptionalUserSecurityAssignmentsDTO):
    pass
