# coding: utf-8

"""
    Visier User Management APIs

    Visier APIs for managing users within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_user_management_python_sdk.type.permission_response_dto import PermissionResponseDTO

class RequiredUserGroupGetAPIResponseDTO(TypedDict):
    pass

class OptionalUserGroupGetAPIResponseDTO(TypedDict, total=False):
    # The unique identifier associated with the user group.
    userGroupId: str

    # An identifiable user group name to display in Visier, such as \"Leadership User Group\".
    displayName: str

    # A list of objects representing the user's permissions.
    permissions: typing.List[PermissionResponseDTO]

class UserGroupGetAPIResponseDTO(RequiredUserGroupGetAPIResponseDTO, OptionalUserGroupGetAPIResponseDTO):
    pass
