# coding: utf-8

"""
    Visier User Management APIs

    Visier APIs for managing users within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredUserCreationAPIRequestDTO(TypedDict):
    pass

class OptionalUserCreationAPIRequestDTO(TypedDict, total=False):
    # The user's username. This is typically the user's email, such as john@visier.com.
    username: str

    # An identifiable name to display within Visier. For example, \"John Smith\".
    displayName: str

    # If applicable, and if available, the user employee ID in the data.
    employeeId: str

    # If false, the user account is disabled.
    accountEnabled: str

    # The user's email. This is used if the user's email is different from their username. For example, \"john.doe@visier.com\".
    email: str

class UserCreationAPIRequestDTO(RequiredUserCreationAPIRequestDTO, OptionalUserCreationAPIRequestDTO):
    pass
