# coding: utf-8

"""
    Visier User Management APIs

    Visier APIs for managing users within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredUserUpdateAPIRequestDTO(TypedDict):
    pass

class OptionalUserUpdateAPIRequestDTO(TypedDict, total=False):
    # An identifiable name to display within Visier. For example, \"John Smith\".
    displayName: str

    # If applicable, and if available, the user employee ID in the data.
    employeeId: str

    # If true, the user account is enabled.
    accountEnabled: str

    # The user's email address.
    email: str

class UserUpdateAPIRequestDTO(RequiredUserUpdateAPIRequestDTO, OptionalUserUpdateAPIRequestDTO):
    pass
