# coding: utf-8

"""
    Visier User Management APIs

    Visier APIs for managing users within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_user_management_python_sdk.type.all_permissions_assigned_for_local_tenant_dto import AllPermissionsAssignedForLocalTenantDTO
from visier_user_management_python_sdk.type.all_profile_assigned_for_local_tenant_dto import AllProfileAssignedForLocalTenantDTO
from visier_user_management_python_sdk.type.all_user_groups_assigned_for_local_tenant_dto import AllUserGroupsAssignedForLocalTenantDTO
from visier_user_management_python_sdk.type.last_login_dto import LastLoginDTO

class RequiredUserGetAPIResponseDTO(TypedDict):
    pass

class OptionalUserGetAPIResponseDTO(TypedDict, total=False):
    # The unique identifier associated with the user.
    userId: str

    # The user's username. This is typically the user's email, such as john@jupiter.com.
    username: str

    # An identifiable name to display within Visier. For example, \"John Smith\".
    displayName: str

    # If applicable, and if available, the user employee ID in the data.
    employeeId: str

    # If false, the user account is disabled.
    accountEnabled: bool

    # A list of objects representing the list of available profiles.
    profiles: AllProfileAssignedForLocalTenantDTO

    # A list of objects representing the user's permissions.
    permissions: AllPermissionsAssignedForLocalTenantDTO

    # A list of objects representing the available user groups.
    userGroups: AllUserGroupsAssignedForLocalTenantDTO

    # An object that represents the time that the user last logged into Visier.
    lastLogin: LastLoginDTO

    # The user's email address.
    email: str

class UserGetAPIResponseDTO(RequiredUserGetAPIResponseDTO, OptionalUserGetAPIResponseDTO):
    pass
