# coding: utf-8

"""
    Visier User Management APIs

    Visier APIs for managing users within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_user_management_python_sdk.type.user_group_get_api_response_dto import UserGroupGetAPIResponseDTO

class RequiredUserGroupsGetAPIResponseDTO(TypedDict):
    pass

class OptionalUserGroupsGetAPIResponseDTO(TypedDict, total=False):
    # A list of user groups.
    userGroups: typing.List[UserGroupGetAPIResponseDTO]

    # The number of results to return. The maximum number of users to retrieve is 1000.
    limit: int

    # The index to start retrieving results from, also known as offset.
    start: int

class UserGroupsGetAPIResponseDTO(RequiredUserGroupsGetAPIResponseDTO, OptionalUserGroupsGetAPIResponseDTO):
    pass
