# coding: utf-8

"""
    Visier User Management APIs

    Visier APIs for managing users within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_user_management_python_sdk.type.users_api_error_message_dto import UsersAPIErrorMessageDTO

class RequiredUsersAPIFailureDTO(TypedDict):
    pass

class OptionalUsersAPIFailureDTO(TypedDict, total=False):
    # The unique identifier associated with the user.
    userId: str

    # The user's username. This is typically the user's email, such as john@jupiter.com.
    userName: str

    # An identifiable name to display within Visier. For example, \"John Smith\".
    displayName: str

    # The error thrown during creation.
    error: UsersAPIErrorMessageDTO

class UsersAPIFailureDTO(RequiredUsersAPIFailureDTO, OptionalUsersAPIFailureDTO):
    pass
