# coding: utf-8

"""
    Visier User Management APIs

    Visier APIs for managing users within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_user_management_python_sdk.type.users_update_api_user_dto import UsersUpdateAPIUserDTO

class RequiredUsersUpdateAPIRequestDTO(TypedDict):
    pass

class OptionalUsersUpdateAPIRequestDTO(TypedDict, total=False):
    users: typing.List[UsersUpdateAPIUserDTO]

class UsersUpdateAPIRequestDTO(RequiredUsersUpdateAPIRequestDTO, OptionalUsersUpdateAPIRequestDTO):
    pass
