# coding: utf-8

"""
    Visier User Management APIs

    Visier APIs for managing users within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredUserCreationAPIResponseDTO(TypedDict):
    pass

class OptionalUserCreationAPIResponseDTO(TypedDict, total=False):
    # The unique identifier associated with the user.
    userId: str

    # The user's username. This is typically the user's email, such as john@jupiter.com.
    username: str

    # An identifiable name to display within Visier. For example, \"John Smith\".
    displayName: str

    # If applicable, and if available, the user employee ID in the data.
    employeeId: str

    # If true, the user account is enabled.
    accountEnabled: str

    # The user's email address.
    email: str

class UserCreationAPIResponseDTO(RequiredUserCreationAPIResponseDTO, OptionalUserCreationAPIResponseDTO):
    pass
