# coding: utf-8

"""
    Visier User Management APIs

    Visier APIs for managing users within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

import unittest
from unittest.mock import patch

import urllib3

import visier_user_management_python_sdk
from visier_user_management_python_sdk.paths.v1_admin_permissions_users import delete
from visier_user_management_python_sdk import configuration, schemas, api_client

from .. import ApiTestMixin


class TestV1AdminPermissionsUsers(ApiTestMixin, unittest.TestCase):
    """
    V1AdminPermissionsUsers unit test stubs
        Remove permissions from users
    """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    response_status = 200






if __name__ == '__main__':
    unittest.main()
